### ISSUE TITLE
Antivirus software removes Latest MGSFPSUnlock.asi

### ISSUE THREAD

**Issue by mgsfox** [cipherxof/MGSFPSUnlock#2]
As like given title, Antivirus software seems to remove latest version MGSFPSUnlock.asi . But your initial version 1.0 doesn't seem to affect by any of it.

**Comment by cipherxof** [comment]
I don't think there's much I can do about this. It's a DLL that injects into a processes memory. Some AVs might flag it.

**Comment by ThirteenAG** [comment]
You can add VersionInfo resource ([example](https://github.com/CookiePLMonster/SilentPatchScarface/blob/master/source/resources/VersionInfo.rc)). Also, on an unrelated note, I suggest to use InitializeASI export instead of DllMain ([example](https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/source/demo_plugins/OverloadFromFolderDLL.cpp#L254)).
